# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataNode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataNode.proto',
  package='dataNode',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x61taNode.proto\x12\x08\x64\x61taNode\"4\n\x0c\x64\x61taNodeInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\"\x1e\n\rClientRespond\x12\r\n\x05state\x18\x01 \x01(\r\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\" \n\x11\x43lientReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\"1\n\x12\x43lientWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"G\n\x11\x43lientSyncRequest\x12%\n\x05nodes\x18\x01 \x03(\x0b\x32\x16.dataNode.dataNodeInfo\x12\x0b\n\x03key\x18\x02 \x01(\r\"C\n\x13\x43lientCreateRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"\"\n\x13\x43lientDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\r2\xd9\x02\n\x08\x64\x61taNode\x12\x46\n\ndeleteFile\x12\x1d.dataNode.ClientDeleteRequest\x1a\x17.dataNode.ClientRespond\"\x00\x12\x38\n\x04read\x12\x1b.dataNode.ClientReadRequest\x1a\x0f.dataNode.Chunk\"\x00\x30\x01\x12\x42\n\x05write\x12\x1c.dataNode.ClientWriteRequest\x1a\x17.dataNode.ClientRespond\"\x00(\x01\x12\x42\n\x06\x63reate\x12\x1d.dataNode.ClientCreateRequest\x1a\x17.dataNode.ClientRespond\"\x00\x12\x43\n\tsyncWrite\x12\x1b.dataNode.ClientSyncRequest\x1a\x17.dataNode.ClientRespond\"\x00\x62\x06proto3'
)




_DATANODEINFO = _descriptor.Descriptor(
  name='dataNodeInfo',
  full_name='dataNode.dataNodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dataNode.dataNodeInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='dataNode.dataNodeInfo.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='dataNode.dataNodeInfo.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=80,
)


_CLIENTRESPOND = _descriptor.Descriptor(
  name='ClientRespond',
  full_name='dataNode.ClientRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='dataNode.ClientRespond.state', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=112,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='dataNode.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='dataNode.Chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=137,
)


_CLIENTREADREQUEST = _descriptor.Descriptor(
  name='ClientReadRequest',
  full_name='dataNode.ClientReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dataNode.ClientReadRequest.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=171,
)


_CLIENTWRITEREQUEST = _descriptor.Descriptor(
  name='ClientWriteRequest',
  full_name='dataNode.ClientWriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dataNode.ClientWriteRequest.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buffer', full_name='dataNode.ClientWriteRequest.buffer', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=222,
)


_CLIENTSYNCREQUEST = _descriptor.Descriptor(
  name='ClientSyncRequest',
  full_name='dataNode.ClientSyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='dataNode.ClientSyncRequest.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='dataNode.ClientSyncRequest.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=295,
)


_CLIENTCREATEREQUEST = _descriptor.Descriptor(
  name='ClientCreateRequest',
  full_name='dataNode.ClientCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dataNode.ClientCreateRequest.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='dataNode.ClientCreateRequest.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='dataNode.ClientCreateRequest.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=364,
)


_CLIENTDELETEREQUEST = _descriptor.Descriptor(
  name='ClientDeleteRequest',
  full_name='dataNode.ClientDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dataNode.ClientDeleteRequest.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=400,
)

_CLIENTSYNCREQUEST.fields_by_name['nodes'].message_type = _DATANODEINFO
DESCRIPTOR.message_types_by_name['dataNodeInfo'] = _DATANODEINFO
DESCRIPTOR.message_types_by_name['ClientRespond'] = _CLIENTRESPOND
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['ClientReadRequest'] = _CLIENTREADREQUEST
DESCRIPTOR.message_types_by_name['ClientWriteRequest'] = _CLIENTWRITEREQUEST
DESCRIPTOR.message_types_by_name['ClientSyncRequest'] = _CLIENTSYNCREQUEST
DESCRIPTOR.message_types_by_name['ClientCreateRequest'] = _CLIENTCREATEREQUEST
DESCRIPTOR.message_types_by_name['ClientDeleteRequest'] = _CLIENTDELETEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

dataNodeInfo = _reflection.GeneratedProtocolMessageType('dataNodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _DATANODEINFO,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.dataNodeInfo)
  })
_sym_db.RegisterMessage(dataNodeInfo)

ClientRespond = _reflection.GeneratedProtocolMessageType('ClientRespond', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPOND,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.ClientRespond)
  })
_sym_db.RegisterMessage(ClientRespond)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

ClientReadRequest = _reflection.GeneratedProtocolMessageType('ClientReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREADREQUEST,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.ClientReadRequest)
  })
_sym_db.RegisterMessage(ClientReadRequest)

ClientWriteRequest = _reflection.GeneratedProtocolMessageType('ClientWriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTWRITEREQUEST,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.ClientWriteRequest)
  })
_sym_db.RegisterMessage(ClientWriteRequest)

ClientSyncRequest = _reflection.GeneratedProtocolMessageType('ClientSyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSYNCREQUEST,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.ClientSyncRequest)
  })
_sym_db.RegisterMessage(ClientSyncRequest)

ClientCreateRequest = _reflection.GeneratedProtocolMessageType('ClientCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCREATEREQUEST,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.ClientCreateRequest)
  })
_sym_db.RegisterMessage(ClientCreateRequest)

ClientDeleteRequest = _reflection.GeneratedProtocolMessageType('ClientDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTDELETEREQUEST,
  '__module__' : 'dataNode_pb2'
  # @@protoc_insertion_point(class_scope:dataNode.ClientDeleteRequest)
  })
_sym_db.RegisterMessage(ClientDeleteRequest)



_DATANODE = _descriptor.ServiceDescriptor(
  name='dataNode',
  full_name='dataNode.dataNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=403,
  serialized_end=748,
  methods=[
  _descriptor.MethodDescriptor(
    name='deleteFile',
    full_name='dataNode.dataNode.deleteFile',
    index=0,
    containing_service=None,
    input_type=_CLIENTDELETEREQUEST,
    output_type=_CLIENTRESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='dataNode.dataNode.read',
    index=1,
    containing_service=None,
    input_type=_CLIENTREADREQUEST,
    output_type=_CHUNK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='write',
    full_name='dataNode.dataNode.write',
    index=2,
    containing_service=None,
    input_type=_CLIENTWRITEREQUEST,
    output_type=_CLIENTRESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='create',
    full_name='dataNode.dataNode.create',
    index=3,
    containing_service=None,
    input_type=_CLIENTCREATEREQUEST,
    output_type=_CLIENTRESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='syncWrite',
    full_name='dataNode.dataNode.syncWrite',
    index=4,
    containing_service=None,
    input_type=_CLIENTSYNCREQUEST,
    output_type=_CLIENTRESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATANODE)

DESCRIPTOR.services_by_name['dataNode'] = _DATANODE

# @@protoc_insertion_point(module_scope)
